#!/usr/bin/env bash

# Check if correct number of arguments is provided

if [ $# -ne 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit 1;
else

# Transfer file using scp with strict host key checking disabled
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
