#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx without using systemctl
service nginx restart
