#!/usr/bin/env bash
# Install Nginx

apt-get -y update
apt-get -y install nginx

# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Create a simple HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx without using systemctl
service nginx restart
