#!/usr/bin/env bash
# generates MySQL dump of all databases 
# creates compressed tar.gz archive for backup

# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
