#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs
apt-get update
apt-get install -y nginx
systemctl start nginx
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
systemctl reload nginx
