#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

PID_FILE="/var/run/my_process.pid"

start_process() {
	./manage_my_process &
	echo "$!" > "$PID_FILE"
	echo "manage_my_process started"
}

stop_process() {
	echo "manage_my_process stopped"
	kill -TERM "$(cat "$PID_FILE")"
	rm "$PID_FILE"
}

restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}

if [ "${1}" == "start" ]; then
	start_process
elif [ "${1}" == "stop" ]; then
	stop_process
elif [ "${1}" == "restart" ]; then
	restart_process
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
