#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely.
# With a sleep 2 in between each iteration,
# Responds to SIGTERM signal with "I am invincible!!!"

while true; do
	echo "To infinity and beyond"
	sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
