#!/usr/bin/env bash
# This script displays username, user id, and home directory path for each user in /etc/passwd.

# Use a while loop to read each line from /etc/passwd
while IFS=':' read -r username _ uid _ _ home _; do
	echo "$username:$uid:$home"
done < /etc/passwd
